### ISSUE TITLE
Exploring Future Activity for llm-ls: Interest from Theia IDE Team

### ISSUE THREAD

**Issue by JonasHelming** [huggingface/llm-ls#110]
Hello llm-ls maintainers,

We at the [Theia IDE](https://theia-ide.org/#theiaide) (with [AI support](https://eclipsesource.com/blogs/2024/10/08/introducting-ai-theia-ide/)) and [Theia AI](https://eclipsesource.com/blogs/2024/10/07/introducing-theia-ai/) find your project incredibly interesting. In fact, we've been exploring similar approaches to enhance AI-powered code completion in the Theia IDE, and the work that llm-ls has already done seems like a great fit for what we need. Since Theia IDE is compatible with VS Code extensions, llm-ls integrates seamlessly, and we'd love to recommend a fully open standard solution like yours to our users. We're even considering including the extension by default.

However, I have a bit of a concern regarding the project's current activity. It looks like llm-ls was actively developed in the first half of the year, but recently, I’ve noticed several bug reports and pull requests that seem to be unanswered (specifically also in llm-vscode), and activity appears to have slowed. This is not meant as a critique—priorities and circumstances change, and I totally understand that.

Before we move ahead with a deeper evaluation, we'd appreciate knowing more about the future plans for llm-ls. Do you foresee resuming active development, perhaps supporting newer models in the future? And are you open to responding to bug reports or reviewing contributions?

We’re genuinely excited about what you've built and would love to work alongside you if the project will continue to evolve. That said, we also completely understand if the current maintainers aren’t looking to dedicate as much time to it moving forward. Gaining adopters for a project can be a huge opportunity to improve and expand the solution, but it naturally also comes with additional effort.

Thanks so much for your time, and looking forward to hearing from you.

Best regards,
Jonas

Project Lead, [Theia IDE](https://theia-ide.org/#theiaide) and [Theia AI](https://eclipsesource.com/blogs/2024/10/07/introducing-theia-ai/)

**Comment by McPatate** [comment]
Hello @JonasHelming, thank you for showing interest in the project. You are correct about the maintenance status of the project, I've been putting it aside for a while.

Would you want to become a maintainer and lead the project? I'd be happy to offer guidance and help review.

There also has been another attempt at this over here: https://github.com/SilasMarvin/lsp-ai, I'd suggest you take a look! Maybe @SilasMarvin can confirm if the project is still maintained?

I'm open to resuming work on `llm-ls`, but I'd have to have a compelling reason to do so, which I haven't found as of yet and explaining why I dropped maintenance here.

**Comment by JonasHelming** [comment]
Hi @McPatate ,

Thank you for your openness and transparency about the state of the project; it’s really appreciated!

To be honest, one of the reasons we were exploring this project was to avoid maintaining exactly this part ourselves—adapting the code completion to specific LLMs. That said, if we decide to move forward with something in this area, we’d likely reimplement parts of it in TypeScript, at least for selected models like StarCoder, as Rust isn’t currently part of our core expertise.

Out of curiosity (and without any offense intended), could you share the original motivation behind creating this project? Understanding that would really help us think about any potential reasons for future contributions or collaboration from your side (you kind of open this question :-)

Thanks again for your insights, and I’ll also check out the other project you mentioned!

Best regards,  
Jonas

**Comment by SilasMarvin** [comment]
> Hello @JonasHelming, thank you for showing interest in the project. You are correct about the maintenance status of the project, I've been putting it aside for a while.
> 
> Would you want to become a maintainer and lead the project? I'd be happy to offer guidance and help review.
> 
> There also has been another attempt at this over here: https://github.com/SilasMarvin/lsp-ai, I'd suggest you take a look! Maybe @SilasMarvin can confirm if the project is still maintained?
> 
> I'm open to resuming work on `llm-ls`, but I'd have to have a compelling reason to do so, which I haven't found as of yet and explaining why I dropped maintenance here.

Hey @JonasHelming. Thanks for the mention @McPatate. For what its worth, LSP-AI is technically still maintained as I do use it everyday, but I would say it has pretty much ever feature I want to give it right now. 

I'm pretty much in the same position as @McPatate I'm open to adding new features for LSP-AI but I can't really find any compelling that I don't already have in.

Best of luck on your project!

**Comment by JonasHelming** [comment]
I am closing this, as there was no further response. Thanks guys for the information!

**Comment by McPatate** [comment]
Hey! Sorry for the delayed response.

> we’d likely reimplement parts of it in TypeScript [..]  as Rust isn’t currently part of our core expertise

Understandable! In that case it might not be the best fit for your project.

> Out of curiosity (and without any offense intended), could you share the original motivation behind creating this project? Understanding that would really help us think about any potential reasons for future contributions or collaboration from your side (you kind of open this question :-)

The idea of having a language server was to have a common backend so that extension development is/was easier. We have three extensions using `llm-ls` as a backend:
- https://github.com/huggingface/llm.nvim
- https://github.com/huggingface/llm-intellij
- https://github.com/huggingface/llm-vscode

Given most IDEs support the LSP and development in extensions is not necessarily comfortable (e.g. http calls in lua from neovim), it made sense to have a Rust (or any other language for that matter) backend.

**Comment by JonasHelming** [comment]
Thank you for your answer! "Out of curiosity (and without any offense intended), could you share the original motivation behind creating this project?" => this was actually not a technical question. Technically, the architecture makes perfect sense to me!

The question was more directed at the motivation to initiate this project, because you mentioned you would need a compelling reason to continue. So I wanted to understand the background why the project was initiated. Of course I am fine if you do not want to share these details.

**Comment by ZerdoX-x** [comment]
@JonasHelming Try considering Tauri in Theia editor or alternative runtime to an Electron and rust will not be a problem.

**Comment by JonasHelming** [comment]
@ZerdoX-x  Thank you, but it is not about the runtime, we can integrate any language on the backend.
