### ISSUE TITLE
Response from generated text includes tokens when using extension

### ISSUE THREAD

**Issue by cmosguy** [huggingface/llm-ls#29]
Hey @McPatate -

If you do not mind me asking, if I am not using the `text-generation-inference`  sserver from huggingface, and instead instead: https://github.com/LucienShui/huggingface-vscode-endpoint-server

![image](https://github.com/huggingface/llm-ls/assets/1676382/dd460fb8-8a77-4eaa-bfb6-55568a4fcf7c)

Is there something in the extension that was supposed to take the <fim-middle> and automatically clean out the tokens and place in the editor or am I supposed to scrub the response on the server side only?

**Comment by cmosguy** [comment]
Yeah, I got stuck on installing the TGI on our severs because of this cargo build issue:

```
   Compiling unicode_categories v0.1.1
   Compiling rand v0.8.5
   Compiling nom v7.1.3
   Compiling nohash-hasher v0.2.0
   Compiling ordered-float v3.9.1
   Compiling clap_builder v4.4.6
   Compiling hostname v0.3.1
   Compiling crossbeam-deque v0.8.3
   Compiling utoipa-swagger-ui v3.1.5
   Compiling sha2 v0.10.8
   Compiling flume v0.11.0
   Compiling mime_guess v2.0.4
The following warnings were emitted during compilation:
warning: /tmp/ccULKIi9.s: Assembler messages:
warning: /tmp/ccULKIi9.s:13: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:13: Error: junk at end of line, first unrecognized character is `-'
warning: /tmp/ccULKIi9.s:15: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:15: Error: unknown pseudo-op: `.lvu1'
warning: /tmp/ccULKIi9.s:16: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:16: Error: unknown pseudo-op: `.lvu2'
```
I have no idea how to resolve the cargo build in the https://github.com/huggingface/text-generation-inference

Sorry to bring it up here in this discussion, but would you happen to know how to resolve this?

**Comment by cmosguy** [comment]
@McPatate I posted my issue here: https://github.com/huggingface/text-generation-inference/issues/1135

But if you have any words of wisdom with your expertise here, because  I think this is related to rust/cargo -- I would be grateful!

Cheers!

**Comment by McPatate** [comment]
I'd never seen assembler warnings before 😄 

I'll reply in the TGI issue and close this one to keep one thread.
