### ISSUE TITLE
Too much logging

### ISSUE THREAD

**Issue by cmosguy** [huggingface/llm-ls#35]
Hey @McPatate,

There is way too much logging going on:
![image](https://github.com/huggingface/llm-ls/assets/1676382/155b1b68-326a-4165-b710-1dae1fdc1f5a)

I set 
```json
   "llm.lsp.logLevel": "warn",
```
but it logs multiple times a second, this is not necessary.  How do I stop this, the `   "llm.lsp.logLevel": "warn",` does nothing to change things.

**Comment by McPatate** [comment]
I'm preparing a fix in https://github.com/huggingface/llm-vscode to allow you to control the log of the output channel.

**Comment by cmosguy** [comment]
Wonderful @McPatate  good work!

**Comment by McPatate** [comment]
<img width="610" alt="Screenshot 2023-10-19 at 17 46 38" src="https://github.com/huggingface/llm-ls/assets/9112841/beb0f809-9eb8-474b-88d9-53172af4a958">

With ^ you should be able to set the log level of the output channel to Warning
