### ISSUE TITLE
Unauthenticated warning should not show when a custom backend is used

### ISSUE THREAD

**Issue by spew** [huggingface/llm-ls#68]
When supplying a custom backend for the `model` parameter along with no access token (such as a self-hosted TGI), the following message shows:

`You are currently unauthenticated and will get rate limited. To reduce rate limiting, login with your API Token and consider subscribing to PRO: https://huggingface.co/pricing#pro"`

This should not show when a custom backend is being used.

Relevant code: https://github.com/huggingface/llm-ls/blob/16606e5371a1b0582543f03fd8a2666f7bf2580a/crates/llm-ls/src/main.rs#L616

**Comment by DanielAdari** [comment]
A hack around this, until this is fixed...

Provide a random token, even if your backend ignores it. The message won't pop-up.

I agree, definitely needs a fix!

**Comment by HennerM** [comment]
This will be addressed by https://github.com/huggingface/llm-ls/pull/58
