### ISSUE TITLE
refactor: adaptor list should be an enum

### ISSUE THREAD

**Issue by McPatate** [huggingface/llm-ls#69]
https://github.com/huggingface/llm-ls/blob/16606e5371a1b0582543f03fd8a2666f7bf2580a/crates/llm-ls/src/adaptors.rs#L209-L213 could be replaced by an enum

**Comment by jeremyelalouf** [comment]
Hi @McPatate, if it is still needed (which i think), I would be more than happy to do it :)

**Comment by McPatate** [comment]
Ah forgot to link the issue with my PR, sorry, I just did it yesterday. Thanks for offering though!

I'll try to keep my list of features to do up to date so that people can contribute if they want :)

**Comment by jeremyelalouf** [comment]
Okay nice although I'm sad, i really wanted to participate, do you know a good first issue for me ?

**Comment by McPatate** [comment]
Not that I can think of at the moment, sorry!

**Comment by McPatate** [comment]
Actually there might be a thing, @rojas-diego has offered to add support for multiple encodings in #50.

Not sure if he's still aiming to do it, feel free to take a stab at it :)

The gist: https://gist.github.com/rojas-diego/04d9c4e3fff5f8374f29b9b738d541ef

**Comment by rojas-diego** [comment]
Hi @McPatate and @jeremyelalouf!

Funny enough Jeremy and I studied at school together in Paris. I'd be happy to get on a call with you Jeremy anytime to collaborate on merging my Gist if you're interested in contributing to the repo!

**Comment by McPatate** [comment]
Epitech est un petit monde :)

**Comment by jeremyelalouf** [comment]
Hi @McPatate and @rojas-diego,

Of course, I'm excited about the opportunity to collaborate with you Diego. If there's any way I can assist you, please don't hesitate to reach out 😄
